---
- hosts: localhost
  connection: local
  gather_facts: yes

  vars:
    fqdn_host: "phun.bit"
    plex_download_url: 'https://downloads.plex.tv/plex-media-server/0.9.11.7.803-87d0708/plexmediaserver_0.9.11.7.803-87d0708_i386.deb' 
    deluged_user: media
    couchpotato_user: media
    sickbeard_user: media
    htpc_manager_user: media
    nzbtomedia_user: media

  roles:
    - plex
    - deluge
    - couchpotato
    - sickbeard
    # -------------
    - nzbtomedia
    - htpc-manager
    # -------------
    - { role: reverse_proxy, service_name: plex, dest_port: "{{plex_port}}", listen_port: 80}
    - { role: reverse_proxy, service_name: deluge, dest_port: "{{deluged_port}}", listen_port: 80}
    - { role: reverse_proxy, service_name: couchpotato, dest_port: "{{couchpotato_port}}", listen_port: 80}
    - { role: reverse_proxy, service_name: sickbeard, dest_port: "{{sickbeard_port}}", listen_port: 80}
    - { role: reverse_proxy, service_name: htpc, dest_port: "{{htpc_manager_port}}", listen_port: 80}
