---
- name: Install Requirements
  apt: pkg={{ item }} state=installed
  with_items:
    - python-cheetah
    - git
    - python-setproctitle

- name: Ensure sickbeard group is created.
  group: name={{ sickbeard_user }} state=present

- name: Ensure sickbeard user is created.
  user: name={{ sickbeard_user }} group={{ sickbeard_user }} state=present

- name: Create installation directory.
  file: path={{ item }} owner={{ sickbeard_user }} group={{ sickbeard_user }} mode=0755 state=directory
  with_items:
    - /opt/sickbeard
    - /var/run/sickbeard

- name: Get SickBeard Code from GitHub
  git: repo={{ sickbeard_repo }} dest=/opt/sickbeard version={{ sickbeard_branch }}

- name: Make sure sickbeard directories have correct ownership
  file: path={{ item }} owner={{ sickbeard_user }} group={{ sickbeard_user }} recurse=yes
  with_items:
    - /opt/sickbeard
    - /var/run/sickbeard

- name: Update SickBeard init.d script
  copy: src=init.ubuntu dest=/etc/init.d/sickbeard owner=root group=root mode=0755

- name: Update SickBeard Daemon Configuration
  template: src=etc_default_sickbeard.j2 dest=/etc/default/sickbeard owner=root group=root mode=0644

- name: Create Sickbeard Media folders
  file: path={{ item }} state=directory recurse=yes owner={{ sickbeard_user }} group={{ sickbeard_user }} mode=0775
  with_items:
    - "{{ media_path }}"
    - "{{ media_path }}/{{ tv_folder }}"

# SickBeard Config cannot be updated when the service is running - active running config is saved on stop.
# SickBeard should be stopped first and config reapplied following by sickbeard start.

- name: Update sickbeard config.ini
  template: src=config.ini.j2 dest=/opt/sickbeard/config.ini owner={{ sickbeard_user }} group={{ sickbeard_user }}
  register: sickbeard_updated

- name: Stop Sickbeard before update
  service: name=sickbeard state=stopped
  when: sickbeard_updated.changed

- name: Update sickbeard config.ini
  template: src=config.ini.j2 dest=/opt/sickbeard/config.ini owner={{ sickbeard_user }} group={{ sickbeard_user }}
  when: sickbeard_updated.changed

- name: Enable and Start SickBeard
  service: name=sickbeard state=started enabled=yes
